prepare v0.1.6 for release
insightsengineering/scda pull request #119
Opened 2023-03-10 19:55 UTC by ayogasekaram

closes #118

2023-03-10 20:18 UTC, ayogasekaram commented
merge https://github.com/insightsengineering/scda.2022/pull/110 before.

2023-03-10 20:43 UTC, edelarua requested changes
Same comments as the other PR - otherwise looks fine!

2023-03-10 20:43 UTC, edelarua commented on NEWS.md
>  # scda 0.1.5
Same as `scda.2022` - I would leave older sections as is.

2023-03-10 20:43 UTC, edelarua commented on NEWS.md
> -* Updated examples to use `scda.2022` data.
I would leave this in too.

2023-03-12 23:29 UTC, edelarua approved these changes
Lgtm!

2023-03-13 00:56 UTC, merged